
import { type Tag, type StoredImage, type Artist, HttpError } from "@arttag/types"
import { query } from "../db/pool.mjs"
import config from "../../config.json" with {type : 'json'}
import format from 'pg-format';
import type { QueryResult } from "pg";
import fs from "fs/promises";
import path from "path";
import { newImage } from "../controllers/images-controller.mjs";

const schema = config.schema

/**
 * Store a list of tags.
 * @param tags List of valid string tags
 * @returns QueryResult
 */
export async function storeTags(tags: string[]): Promise<QueryResult<any>> {
    const prepped = tags.map((el, _) => {
        return `(\'${el}\')`
    })
    // TODO: can use `RETURNING *` to get back rows inserted
    const sql = format('INSERT INTO %I.tags (tag) VALUES %s ON CONFLICT DO NOTHING', schema, prepped.join(", "))
    // NOTE: Insert a new row into the tags table with a value for the tag column
    
    // console.log(sql);
    return await query(sql);
    // console.log(res);
}

/**
 * Store an artist name.
 * 
 * @param artist Valid string artist name
 * @returns QueryResult
 */
export async function storeArtist(artist: string): Promise<QueryResult<any>> {
        const prepped = `(\'${artist}\')`;
        const sql = format('INSERT INTO %I.artists (name) VALUES %s ON CONFLICT DO NOTHING', schema, prepped);
        // NOTE: Insert a new row into the artists table with a value for the names column
        return await query(sql);
}

/**
 * Store an image with tags and other parameters
 * 
 * @param file Image file in buffer
 * @param filetype Filetype of image (file extension without ".")
 * @param tags List of tags for iamge
 * @param hash Calculated hash of image file
 * @param artist Artist name for image
 * @param url Source url for image
 * @param nsfw Is the image nsfw?
 * @returns Newly stored image
 */
export async function storeImage(
    file: Buffer,
    filetype: string,
    tags: string[],
    hash: string,
    artist: string,
    url : string,
    nsfw : boolean
): Promise<StoredImage> {
    const args = [
        schema,
        url,
        artist,
        hash,
        hash.substring(0, 16),
        hash.substring(16, 32),
        hash.substring(32, 48),
        hash.substring(48, 64),
        filetype,
        String(nsfw)
    ]

    try {
        // begin transaction
        await query("BEGIN");

        // Step 1: insert row to images table
        let template = `INSERT INTO %I.images 
                (src_url, artist, hash, hash_slice_1, hash_slice_2, hash_slice_3, hash_slice_4, file_type, nsfw) 
                VALUES (%s, '%s', '%s', '%s', '%s', '%s', '%s', '%s', %s) RETURNING *`
        let sql = format.withArray(template, args)
        // console.log(sql)
        const imageRes = await query(sql);
        const newImageRow = imageRes.rows[0];
        // const id = row.image_id
        // console.log(qres)

        // Step 2: add rows to tagged_images table
        template = `INSERT INTO %I.tagged_images (tag, image_id) VALUES %s`
        const new_rows = tags.map((tag, _) => {
            return `('${tag}', ${newImageRow.image_id})`
        })
        sql = format(template, schema, new_rows.join(", "))
        // console.log(sql)
        await query(sql);

        // Step 3: try to save file to disk
        const filePath = path.join(config.imagesFolder, newImageRow.filename)
        // NOTE: use filename automagically generated by database
        await fs.writeFile(filePath, file)
        console.info(`[INFO] Successfully wrote ${filePath}`)
        
        // complete transaction
        await query("COMMIT");

        // return data we inserted
        return {
            "image_id" : newImageRow.image_id,
            "filename" : newImageRow.filename,
            "file_type" : newImageRow.file_type,
            "src_url" : newImageRow.src_url,
            "artist" : newImageRow.artist,
            "nsfw" : newImageRow.nsfw,
            "hash" : newImageRow.hash,
            "time_created" : newImageRow.time_created,
            "last_updated" : newImageRow.last_updated
        };
    }
    catch (error) {
        // roll back database transaction if error is encountered
        await query("ROLLBACK");
        
        // TODO: make/use a DBError class instead?
        throw new HttpError(500, "storeImage: " + error);
    }
}